### ISSUE TITLE
Separate settings for each queue

### ISSUE THREAD

**Issue by nilpoona** [aws/aws-activejob-sqs-ruby#4]
Are there any plans to make it possible to configure SQS Active Job settings on a per queue basis, as shown below?

```yaml
queue1:
  max_messages: 10
  visibility_timeout: 30
queue2:
  max_messages: 5
  visibility_timeout: 100
```
